/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GitJarUpdate;

import org.junit.Test;

import de.neuwirthinformatik.Alexander.GitJarUpdate.Update;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Update classUnderTest = new Update();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
